### PR TITLE
Request for gentx bara-foundation

### PR DESCRIPTION
**Pull request by nampdn**
Hi, please add bara-foundation.

Thank you!

### CODE REVIEW

**Comment by Jared-TFL** [comment]
does not exist in pre-genesis

**Comment by nampdn** [comment]
Hi @Jared-TFL,
My wallet does has 7M LUNC and was snapshotted in May 27. I don't see where to register `pre-genesis` in the document except this step to submit gentx file.
Could you please help me to figure out or I was not applicable since the beginning of Terra 1.0?

**Comment by awsdataarchitect** [comment]
I think it's closed now. Once genesis and seeds and addresss book are made available you can apply. I missed it too. They did not put clear instructions and closed the discord due to lot of spam

**Comment by nampdn** [comment]
> I think it's closed now. Once genesis and seeds and addresss book are made available you can apply. I missed it too. They did not put clear instructions and closed the discord due to lot of spam

Thank you! Hopefully we can apply it later

**Pull request closed without merging**
